///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HOTEL_PLANISPHERE
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The トップ画面 recording.
    /// </summary>
    [TestModule("7689c5ff-63b1-457c-bccf-0a5f744d46d7", ModuleType.Recording, 1)]
    public partial class トップ画面 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HOTEL_PLANISPHERERepository repository.
        /// </summary>
        public static HOTEL_PLANISPHERERepository repo = HOTEL_PLANISPHERERepository.Instance;

        static トップ画面 instance = new トップ画面();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public トップ画面()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static トップ画面 Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable menuName.
        /// </summary>
        [TestVariable("9bfb6113-ad43-4745-860e-7e6241a2c268")]
        public string menuName
        {
            get { return repo.menuName; }
            set { repo.menuName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.トップページ.メニューボタン' at 35;22.", repo.ApplicationUnderTest.トップページ.メニューボタンInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.トップページ.メニューボタン.Click("35;22");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
