///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HOTEL_PLANISPHERE
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 宿泊予約画面 recording.
    /// </summary>
    [TestModule("4904fa4c-f683-4933-b244-fc3da73e09bc", ModuleType.Recording, 1)]
    public partial class 宿泊予約画面 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HOTEL_PLANISPHERERepository repository.
        /// </summary>
        public static HOTEL_PLANISPHERERepository repo = HOTEL_PLANISPHERERepository.Instance;

        static 宿泊予約画面 instance = new 宿泊予約画面();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 宿泊予約画面()
        {
            term = "{Back}2";
            headCount = "{Back}2";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 宿泊予約画面 Instance
        {
            get { return instance; }
        }

#region Variables

        string _term;

        /// <summary>
        /// Gets or sets the value of variable term.
        /// </summary>
        [TestVariable("9c677268-7840-4108-a40a-38d6ec7a0f8c")]
        public string term
        {
            get { return _term; }
            set { _term = value; }
        }

        string _headCount;

        /// <summary>
        /// Gets or sets the value of variable headCount.
        /// </summary>
        [TestVariable("98ce2a44-82b3-4d0b-909f-9fcf5989d097")]
        public string headCount
        {
            get { return _headCount; }
            set { _headCount = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable date.
        /// </summary>
        [TestVariable("eb19ba77-4143-4fc6-bc7f-5e7a47907140")]
        public string date
        {
            get { return repo.date; }
            set { repo.date = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable addPlan.
        /// </summary>
        [TestVariable("ccd51d0f-a943-49e3-96b6-975d9bbbbf3e")]
        public string addPlan
        {
            get { return repo.addPlan; }
            set { repo.addPlan = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.宿泊予約画面.Date' at 374;27.", repo.ApplicationUnderTest.宿泊予約画面.DateInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.宿泊予約画面.Date.Click("374;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.宿泊予約画面.ATag25' at 8;18.", repo.ApplicationUnderTest.宿泊予約画面.ATag25Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.宿泊予約画面.ATag25.Click("8;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.宿泊予約画面.Term' at 376;24.", repo.ApplicationUnderTest.宿泊予約画面.TermInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.宿泊予約画面.Term.Click("376;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ApplicationUnderTest.宿泊予約画面.Term'.", repo.ApplicationUnderTest.宿泊予約画面.TermInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.宿泊予約画面.Term.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$term' with focus on 'ApplicationUnderTest.宿泊予約画面.Term'.", repo.ApplicationUnderTest.宿泊予約画面.TermInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.宿泊予約画面.Term.PressKeys(term);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.宿泊予約画面.HeadCount' at 350;4.", repo.ApplicationUnderTest.宿泊予約画面.HeadCountInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.宿泊予約画面.HeadCount.Click("350;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ApplicationUnderTest.宿泊予約画面.HeadCount'.", repo.ApplicationUnderTest.宿泊予約画面.HeadCountInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.宿泊予約画面.HeadCount.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$headCount' with focus on 'ApplicationUnderTest.宿泊予約画面.HeadCount'.", repo.ApplicationUnderTest.宿泊予約画面.HeadCountInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.宿泊予約画面.HeadCount.PressKeys(headCount);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.宿泊予約画面.Breakfast' at 7;10.", repo.ApplicationUnderTest.宿泊予約画面.BreakfastInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.宿泊予約画面.Breakfast.Click("7;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'no' on item 'ApplicationUnderTest.宿泊予約画面.Contact'.", repo.ApplicationUnderTest.宿泊予約画面.ContactInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.宿泊予約画面.Contact.Element.SetAttributeValue("TagValue", "no");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.宿泊予約画面.SubmitButton' at 133;21.", repo.ApplicationUnderTest.宿泊予約画面.SubmitButtonInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.宿泊予約画面.SubmitButton.Click("133;21");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
