///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HOTEL_PLANISPHERE
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 宿泊予約確認画面 recording.
    /// </summary>
    [TestModule("80180a75-fb0e-4681-8234-7657d8972682", ModuleType.Recording, 1)]
    public partial class 宿泊予約確認画面 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HOTEL_PLANISPHERERepository repository.
        /// </summary>
        public static HOTEL_PLANISPHERERepository repo = HOTEL_PLANISPHERERepository.Instance;

        static 宿泊予約確認画面 instance = new 宿泊予約確認画面();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 宿泊予約確認画面()
        {
            accommodationFee = "合計 7,875円（税込み）";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 宿泊予約確認画面 Instance
        {
            get { return instance; }
        }

#region Variables

        string _accommodationFee;

        /// <summary>
        /// Gets or sets the value of variable accommodationFee.
        /// </summary>
        [TestVariable("373dd156-d02a-4e57-acde-10ccf1c9fbec")]
        public string accommodationFee
        {
            get { return _accommodationFee; }
            set { _accommodationFee = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText=$accommodationFee) on item 'ApplicationUnderTest.宿泊予約確認画面.TotalBill'.", repo.ApplicationUnderTest.宿泊予約確認画面.TotalBillInfo, new RecordItemIndex(0));
                Validate.AttributeEqual(repo.ApplicationUnderTest.宿泊予約確認画面.TotalBillInfo, "InnerText", accommodationFee, null, new Validate.Options(){ReportScreenshot=Validate.ResultOption.Always});
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.宿泊予約確認画面.この内容で予約する' at 502;15.", repo.ApplicationUnderTest.宿泊予約確認画面.この内容で予約するInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.宿泊予約確認画面.この内容で予約する.Click("502;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.宿泊予約確認画面.ButtonTag閉じる' at 30;12.", repo.ApplicationUnderTest.宿泊予約確認画面.ButtonTag閉じるInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.宿泊予約確認画面.ButtonTag閉じる.Click("30;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
