///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HOTEL_PLANISPHERE
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The 宿泊プラン一覧画面 recording.
    /// </summary>
    [TestModule("1a203d1a-271d-41cd-9ebf-ab39e0785494", ModuleType.Recording, 1)]
    public partial class 宿泊プラン一覧画面 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HOTEL_PLANISPHERERepository repository.
        /// </summary>
        public static HOTEL_PLANISPHERERepository repo = HOTEL_PLANISPHERERepository.Instance;

        static 宿泊プラン一覧画面 instance = new 宿泊プラン一覧画面();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public 宿泊プラン一覧画面()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static 宿泊プラン一覧画面 Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable planName.
        /// </summary>
        [TestVariable("6ce347a3-d342-4944-899d-47edd97e4d02")]
        public string planName
        {
            get { return repo.planName; }
            set { repo.planName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.宿泊プラン一覧.このプランで予約' at 95;12.", repo.ApplicationUnderTest.宿泊プラン一覧.このプランで予約Info, new RecordItemIndex(0));
            repo.ApplicationUnderTest.宿泊プラン一覧.このプランで予約.Click("95;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
